title: Ahaan
description: "Ahaan"
owner_name: Ahaan
github_username: Av1922798
github_repo: "Ahaan_2025" 
baseurl: "/Ahaan_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/Av1922798"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@pokespace6784" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/toolsetup.md
  - navigation/search.md
  - navigation/about.md
  - nagvigation/blogs.md
  - README4YML.md
